In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_excel('data for preprocessing.xlsx')

In [ ]:
df

,CRM Name,Year,Week number,Month,Month number,Sent Date,Sent time,End date,Country,Channel,...,Clicks,Day1 Conv.,Conversions,Registrations,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name
0,220108_SA_VAC30_NC-Unregistered_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,-,NaN,52,36,36097.0875,VAC30,0,0,0,30% Off - PPM
1,220108_SA_VAC30_NC-Registered_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,-,NaN,55,-,41670.6,VAC30,0,0,0,30% Off - PPM
2,220108_SA_VAC30_Active_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,-,NaN,313,-,405397.425,VAC30,0,0,0,30% Off - PPM
3,220108_SA_VAC30_Inactive_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,-,NaN,70,-,36317.3625,VAC30,0,0,0,30% Off - PPM
4,220124_SA_MG5_NC-Registered_PN,2022,5,January,1,2022-01-24,19:00:00,NaN,SA,Push Notification,...,-,NaN,157,-,75911.625,NaN,0,0,0,Product marketing - MG5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,231228_SA_DailyAndroid_Inactive_IAM,2023,52,December,12,2023-12-28,19:00:00,2023-12-31 00:00:00,SA,In app message,...,0,0,0,NaN,0,FLA10,NaN,NaN,NaN,Daily offer
1806,231231_SA_NewYear_Active_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,NaN,20,526,NaN,579114.7875,NaN,NaN,NaN,NaN,New Year Eve
1807,231231_SA_NewYear_Inactive_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,NaN,2,150,NaN,133355.7375,NaN,NaN,NaN,NaN,New Year Eve
1808,231231_SA_NewYear_NC-Registered_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,NaN,2,79,NaN,110541.075,NaN,NaN,NaN,NaN,New Year Eve
1809,231231_SA_NewYear_NC-Unregistered_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,NaN,2,58,NaN,13794.3375,NaN,NaN,NaN,NaN,New Year Eve

In [ ]:
df.describe()

,Year,Week number,Month number,Sent Date,Messages Sent,Recipients
count,1810.000000,1810.000000,1810.000000,1810,1810.000000,1810.000000
mean,2022.617680,29.456354,7.085083,2023-03-02 02:24:00,41299.671823,38658.244199
min,2022.000000,1.000000,1.000000,2022-01-08 00:00:00,0.000000,0.000000
25%,2022.000000,15.000000,4.000000,2022-11-18 00:00:00,5578.000000,4421.500000
50%,2023.000000,30.000000,7.000000,2023-02-28 12:00:00,19791.000000,15303.000000
75%,2023.000000,45.000000,11.000000,2023-08-27 00:00:00,61995.750000,59382.000000
max,2023.000000,53.000000,12.000000,2023-12-31 00:00:00,343892.000000,328386.000000
std,0.486089,16.104328,3.638965,NaN,51560.698218,51090.070014

In [ ]:
df.isnull().sum()

CRM Name                   0
Year                       0
Week number                0
Month                      0
Month number               0
Sent Date                  0
Sent time                 22
End date                1538
Country                    0
Channel                    0
Service Type               0
Message type               0
Customer LifeCycle         0
Target                     0
Messages Sent              0
Recipients                 0
Notification opens        22
App opens                130
Clicks                   147
Day1 Conv.              1180
Conversions                1
Registrations            969
Campaing Revenue           2
Voucher Name             661
Control Group Volume     339
Control Group Conv       339
Control Group Rev        346
Campaign Name              0
dtype: int64

In [ ]:
df.replace('-', np.nan, inplace=True)

<ipython-input-209-1ec1a2def20a>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('-', np.nan, inplace=True)

In [ ]:
df.isnull().sum()

CRM Name                   0
Year                       0
Week number                0
Month                      0
Month number               0
Sent Date                  0
Sent time                 22
End date                1538
Country                    0
Channel                    0
Service Type               0
Message type               0
Customer LifeCycle         0
Target                     0
Messages Sent              0
Recipients                 0
Notification opens       138
App opens                259
Clicks                  1174
Day1 Conv.              1181
Conversions                2
Registrations           1727
Campaing Revenue           2
Voucher Name             661
Control Group Volume     941
Control Group Conv       941
Control Group Rev        946
Campaign Name              0
dtype: int64

In [ ]:
df['Sent dayofweek'] = df['Sent Date'].dt.day_name()

In [ ]:
df

,CRM Name,Year,Week number,Month,Month number,Sent Date,Sent time,End date,Country,Channel,...,Day1 Conv.,Conversions,Registrations,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name,Sent dayofweek
0,220108_SA_VAC30_NC-Unregistered_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,NaN,52.0,36,36097.0875,VAC30,0.0,0.0,0,30% Off - PPM,Saturday
1,220108_SA_VAC30_NC-Registered_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,NaN,55.0,NaN,41670.6,VAC30,0.0,0.0,0,30% Off - PPM,Saturday
2,220108_SA_VAC30_Active_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,NaN,313.0,NaN,405397.425,VAC30,0.0,0.0,0,30% Off - PPM,Saturday
3,220108_SA_VAC30_Inactive_PN,2022,2,January,1,2022-01-08,12:00:00,NaN,SA,Push Notification,...,NaN,70.0,NaN,36317.3625,VAC30,0.0,0.0,0,30% Off - PPM,Saturday
4,220124_SA_MG5_NC-Registered_PN,2022,5,January,1,2022-01-24,19:00:00,NaN,SA,Push Notification,...,NaN,157.0,NaN,75911.625,NaN,0.0,0.0,0,Product marketing - MG5,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,231228_SA_DailyAndroid_Inactive_IAM,2023,52,December,12,2023-12-28,19:00:00,2023-12-31 00:00:00,SA,In app message,...,0.0,0.0,NaN,0,FLA10,NaN,NaN,NaN,Daily offer,Thursday
1806,231231_SA_NewYear_Active_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,20.0,526.0,NaN,579114.7875,NaN,NaN,NaN,NaN,New Year Eve,Sunday
1807,231231_SA_NewYear_Inactive_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,2.0,150.0,NaN,133355.7375,NaN,NaN,NaN,NaN,New Year Eve,Sunday
1808,231231_SA_NewYear_NC-Registered_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,2.0,79.0,NaN,110541.075,NaN,NaN,NaN,NaN,New Year Eve,Sunday
1809,231231_SA_NewYear_NC-Unregistered_PN,2023,53,December,12,2023-12-31,12:00:00,NaN,SA,Push Notification,...,2.0,58.0,NaN,13794.3375,NaN,NaN,NaN,NaN,New Year Eve,Sunday

In [ ]:
df.drop(['End date', 'Registrations','Day1 Conv.', 'Clicks', 'Month'], axis=1, inplace=True)

In [ ]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [ ]:
df['Control Group Rev'].fillna(df['Control Group Rev'].mode(), inplace=True)

<ipython-input-215-96a86849df70>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Control Group Rev'].fillna(df['Control Group Rev'].mode(), inplace=True)

In [ ]:
df['Conversions'].fillna(df['Conversions'].median(), inplace=True)

<ipython-input-216-c78d53948ba8>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Conversions'].fillna(df['Conversions'].median(), inplace=True)

In [ ]:
df['open_rate'] = df['Notification opens'] / df['Recipients']
average_open_rate = df['open_rate'].mean(skipna=True)
df['Notification opens'] = df['Notification opens'].fillna(df['Recipients'] * average_open_rate)
df.drop('open_rate', axis=1, inplace=True)

In [ ]:
df['Channel'].fillna(df['Channel'].mode()[0], inplace=True)

<ipython-input-218-8689eeb00e8b>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Channel'].fillna(df['Channel'].mode()[0], inplace=True)

In [ ]:
df['Sent time'] = df['Sent time'].fillna(method='ffill')

<ipython-input-219-9551b3b745d8>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Sent time'] = df['Sent time'].fillna(method='ffill')

In [ ]:
df['Voucher Name'] = df['Voucher Name'].fillna(method='ffill')

<ipython-input-220-8a2f10afd2aa>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Voucher Name'] = df['Voucher Name'].fillna(method='ffill')

In [ ]:
df['Campaing Revenue'].fillna(0, inplace=True)

<ipython-input-221-19cf93a858bd>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Campaing Revenue'].fillna(0, inplace=True)

In [ ]:
df.isnull().sum()

CRM Name                  0
Year                      0
Week number               0
Month number              0
Sent Date                 0
Sent time                 0
Country                   0
Channel                   0
Service Type              0
Message type              0
Customer LifeCycle        0
Target                    0
Messages Sent             0
Recipients                0
Notification opens        0
App opens                 0
Conversions               0
Campaing Revenue          0
Voucher Name              0
Control Group Volume      0
Control Group Conv        0
Control Group Rev       946
Campaign Name             0
Sent dayofweek            0
dtype: int64

In [ ]:
df['Country'] = df['Country'].astype('category').cat.codes
df['Channel'] = df['Channel'].astype('category').cat.codes
df['Service Type'] = df['Service Type'].astype('category').cat.codes
df['Message type'] = df['Message type'].astype('category').cat.codes
df['Voucher Name'] = df['Voucher Name'].astype('category').cat.codes
df['Campaign Name'] = df['Campaign Name'].astype('category').cat.codes
df

,CRM Name,Year,Week number,Month number,Sent Date,Sent time,Country,Channel,Service Type,Message type,...,Notification opens,App opens,Conversions,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name,Sent dayofweek
0,220108_SA_VAC30_NC-Unregistered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,1554.0,5466.0,52.0,36097.0875,39,0.0,0.0,0,7,Saturday
1,220108_SA_VAC30_NC-Registered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,356.0,1440.0,55.0,41670.6,39,0.0,0.0,0,7,Saturday
2,220108_SA_VAC30_Active_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,260.0,1118.0,313.0,405397.425,39,0.0,0.0,0,7,Saturday
3,220108_SA_VAC30_Inactive_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,188.0,645.0,70.0,36317.3625,39,0.0,0.0,0,7,Saturday
4,220124_SA_MG5_NC-Registered_PN,2022,5,1,2022-01-24,19:00:00,0,2,1,3,...,3014.0,9449.0,157.0,75911.625,39,0.0,0.0,0,63,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,231228_SA_DailyAndroid_Inactive_IAM,2023,52,12,2023-12-28,19:00:00,0,1,1,3,...,0.0,1614.0,0.0,0,15,307.0,4.0,NaN,25,Thursday
1806,231231_SA_NewYear_Active_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,377.0,1821.0,526.0,579114.7875,15,307.0,4.0,NaN,54,Sunday
1807,231231_SA_NewYear_Inactive_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,205.0,1334.0,150.0,133355.7375,15,307.0,4.0,NaN,54,Sunday
1808,231231_SA_NewYear_NC-Registered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,172.0,2191.0,79.0,110541.075,15,307.0,4.0,NaN,54,Sunday
1809,231231_SA_NewYear_NC-Unregistered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,649.0,4290.0,58.0,13794.3375,15,307.0,4.0,NaN,54,Sunday

In [ ]:
df['CRM Name'].describe()

count                                         1810
unique                                        1793
top       221121_SA_ReminderMonthly10%_Inactive_PN
freq                                             2
Name: CRM Name, dtype: object

In [ ]:
df[df.duplicated()]

,CRM Name,Year,Week number,Month number,Sent Date,Sent time,Country,Channel,Service Type,Message type,...,Notification opens,App opens,Conversions,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name,Sent dayofweek
633,221221_SA_ReminderMonthly10%_NC-Registered_SMS,2022,52,12,2022-12-21,10:00:00,0,3,1,2,...,445.0,522.0,26.0,32741.9296,12,3948.0,182.0,2846.0192,48,Wednesday

In [ ]:
df = df.drop_duplicates()

In [ ]:
df['Control Group Rev'].replace('SAR', '', inplace=True)
df

<ipython-input-227-5c22b661a67c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Control Group Rev'].replace('SAR', '', inplace=True)
<ipython-input-227-5c22b661a67c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Control Group Rev'].replace('SAR', '', inplace=True)

,CRM Name,Year,Week number,Month number,Sent Date,Sent time,Country,Channel,Service Type,Message type,...,Notification opens,App opens,Conversions,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name,Sent dayofweek
0,220108_SA_VAC30_NC-Unregistered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,1554.0,5466.0,52.0,36097.0875,39,0.0,0.0,0,7,Saturday
1,220108_SA_VAC30_NC-Registered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,356.0,1440.0,55.0,41670.6,39,0.0,0.0,0,7,Saturday
2,220108_SA_VAC30_Active_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,260.0,1118.0,313.0,405397.425,39,0.0,0.0,0,7,Saturday
3,220108_SA_VAC30_Inactive_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,188.0,645.0,70.0,36317.3625,39,0.0,0.0,0,7,Saturday
4,220124_SA_MG5_NC-Registered_PN,2022,5,1,2022-01-24,19:00:00,0,2,1,3,...,3014.0,9449.0,157.0,75911.625,39,0.0,0.0,0,63,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,231228_SA_DailyAndroid_Inactive_IAM,2023,52,12,2023-12-28,19:00:00,0,1,1,3,...,0.0,1614.0,0.0,0,15,307.0,4.0,NaN,25,Thursday
1806,231231_SA_NewYear_Active_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,377.0,1821.0,526.0,579114.7875,15,307.0,4.0,NaN,54,Sunday
1807,231231_SA_NewYear_Inactive_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,205.0,1334.0,150.0,133355.7375,15,307.0,4.0,NaN,54,Sunday
1808,231231_SA_NewYear_NC-Registered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,172.0,2191.0,79.0,110541.075,15,307.0,4.0,NaN,54,Sunday
1809,231231_SA_NewYear_NC-Unregistered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,649.0,4290.0,58.0,13794.3375,15,307.0,4.0,NaN,54,Sunday

In [ ]:
df['Control Group Rev'].dtype

dtype('O')

In [ ]:
df['Control Group Rev'] = pd.to_numeric(df['Control Group Rev'], errors='coerce')
df['Control Group Rev'] = df['Control Group Rev'].fillna(df['Control Group Rev'].median())

<ipython-input-229-39d9e4e89b84>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Control Group Rev'] = pd.to_numeric(df['Control Group Rev'], errors='coerce')
<ipython-input-229-39d9e4e89b84>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Control Group Rev'] = df['Control Group Rev'].fillna(df['Control Group Rev'].median())

In [ ]:
df['Control Group Rev'].head(30)

0         0.0000
1         0.0000
2         0.0000
3         0.0000
4         0.0000
5         0.0000
6         0.0000
7         0.0000
8         0.0000
9         0.0000
10        0.0000
11    75453.7500
12    86625.0000
13        0.0000
14        0.0000
15        0.0000
16        0.0000
17    65220.0000
18    14361.3000
19        0.0000
20        0.0000
21    27648.3000
22     2860.9125
23        0.0000
24     5699.2500
25      272.5125
26        0.0000
27    26259.7125
28        0.0000
29    12315.3375
Name: Control Group Rev, dtype: float64

In [ ]:
df

,CRM Name,Year,Week number,Month number,Sent Date,Sent time,Country,Channel,Service Type,Message type,...,Notification opens,App opens,Conversions,Campaing Revenue,Voucher Name,Control Group Volume,Control Group Conv,Control Group Rev,Campaign Name,Sent dayofweek
0,220108_SA_VAC30_NC-Unregistered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,1554.0,5466.0,52.0,36097.0875,39,0.0,0.0,0.00000,7,Saturday
1,220108_SA_VAC30_NC-Registered_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,356.0,1440.0,55.0,41670.6,39,0.0,0.0,0.00000,7,Saturday
2,220108_SA_VAC30_Active_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,260.0,1118.0,313.0,405397.425,39,0.0,0.0,0.00000,7,Saturday
3,220108_SA_VAC30_Inactive_PN,2022,2,1,2022-01-08,12:00:00,0,2,1,2,...,188.0,645.0,70.0,36317.3625,39,0.0,0.0,0.00000,7,Saturday
4,220124_SA_MG5_NC-Registered_PN,2022,5,1,2022-01-24,19:00:00,0,2,1,3,...,3014.0,9449.0,157.0,75911.625,39,0.0,0.0,0.00000,63,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,231228_SA_DailyAndroid_Inactive_IAM,2023,52,12,2023-12-28,19:00:00,0,1,1,3,...,0.0,1614.0,0.0,0,15,307.0,4.0,2954.08125,25,Thursday
1806,231231_SA_NewYear_Active_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,377.0,1821.0,526.0,579114.7875,15,307.0,4.0,2954.08125,54,Sunday
1807,231231_SA_NewYear_Inactive_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,205.0,1334.0,150.0,133355.7375,15,307.0,4.0,2954.08125,54,Sunday
1808,231231_SA_NewYear_NC-Registered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,172.0,2191.0,79.0,110541.075,15,307.0,4.0,2954.08125,54,Sunday
1809,231231_SA_NewYear_NC-Unregistered_PN,2023,53,12,2023-12-31,12:00:00,0,2,1,2,...,649.0,4290.0,58.0,13794.3375,15,307.0,4.0,2954.08125,54,Sunday

In [ ]:
df['Control Group Rev'].tail()

1805    2954.08125
1806    2954.08125
1807    2954.08125
1808    2954.08125
1809    2954.08125
Name: Control Group Rev, dtype: float64